- package.json
> https://github.com/vuejs/theme/blob/main/pnpm-lock.yaml
It seems that this project also uses `pnpm` and no longer needs `yarn`.
> chore: change script yarn to npm

- src/vitepress/components/VPContentDoc.vue
This PR fixes the hardcoded link for the "edit this page" feature.
> fix: remove hardcoded repository from edit link

- src/vitepress/components/VPNavBarSearch.vue
Error when algolia does not exist: `Cannot set properties of undefined (setting 'textContent') in VPNavBarSearch.vue:21`.
> fix: error when algolia does not exist

- src/core/styles/vt-doc-custom-blocks.css
When I read the documentation for the new version of Vue.js, I noticed an unusual CSS style:
You can see the address of the documentation [here](https://vuejs.org/guide/essentials/conditional.html#v-if-with-v-for).
As indicated by the text highlighted in the red box above, this style guide is supposed to be a link, but it is the same color as the code (blue), not green elsewhere on the page.
I think all links should be green.
I looked at the Vue.js official documentation repository and found that it used the theme of this repository, and then located the CSS that was in question.
When I removed it (like this modification), it went back to normal:
I think this change is necessary because the green color tells the reader "Oh, this is a link, I need to click on it and see what's written on …
> remove `a` style of `custom-block` class

- src/core/components/VTCodeGroup.vue
- src/core/components/VTCodeGroupTab.vue
- src/core/index.ts
- src/core/styles/index.css
- src/core/styles/vt-code-group.css
Resolves #46 
Adds a VTCodeGroup component to replace https://github.com/vuejs/docs/blob/main/src/guide/scaling-up/TestingApiSwitcher.vue
Also @kiaking it fixes the mobile responsive issues you saw with the original implementation. To test it, I replaced the custom component I pasted above locally. I was looking for a way to demo/test out the component in this repo. Is there any infra for that?
https://user-images.githubusercontent.com/2801156/155276939-631c87b0-94c8-4038-afd8-f52d8662cd3b.mov
> feat: adding VTCodeGroup component to the @vue/theme (#46)

- pnpm-lock.yaml
- src/vitepress/composables/outline.ts
When scrolling through the pages I noticed the side navigation not setting the active visible element correctly.
After looking through the logic of setting active element I noticed that it gets all anchors on the page rather than those that are visible (not `display: none`).
When it was getting all anchors the `activateLink` function couldn't really calculate which was the active element since `nextAnchor` was `display: none` and it couldn't get its offetTop since offsetTop for hidden elements is `null` ([offsetTop docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop#browser_compatibility)) , this way it was setting the next active one to be the hidden one rather than what is currently visible. 
When properly filtering the anchors to get only those that are …
> Fix active element for side navigation

- src/core/styles/vt-doc-code.css
The selector for setting a negative `margin-top` is intended to handle consecutive code samples. However, the part of the selector intended to handle samples nested inside `class="options-api"` or `class="composition-api"` is currently matching all code samples, when it should just be matching those at the start.
I've added `:first-child` so that other code samples are not impacted.
In the current Vue 3 docs there is only one place where this makes a difference. It's in <https://vuejs.org/guide/components/events.html>, when viewed in Options API mode.
**Before (see red arrow):**
**After:**
> fix: avoid setting margin-top for code samples in an edge case

- src/vitepress/config/highlight.js
From `highlighter.codeToHtml(code, lang)` to `highlighter.codeToHtml(code, { lang })`. The previous one is actually already deprecated.
Ref: https://github.com/shikijs/shiki/blob/main/README.md
> Fix a deprecated shiki API

- demo/.vitepress/config.js
- src/core/components/VTHamburger.vue
- src/core/components/VTSwitchAppearance.vue
- src/core/types/menu.ts
- src/vitepress/components/VPAlgoliaSearchBox.vue
- src/vitepress/components/VPAnnouncer.vue
- src/vitepress/components/VPCarbonAds.vue
- src/vitepress/components/VPContentDoc.vue
- src/vitepress/components/VPContentDocFooter.vue
- src/vitepress/components/VPContentDocOutline.vue
- src/vitepress/components/VPFooter.vue
- src/vitepress/components/VPLocalNav.vue
- src/vitepress/components/VPNavBarExtra.vue
- src/vitepress/components/VPNavBarMenu.vue
- src/vitepress/components/VPNavBarSearch.vue
- src/vitepress/components/VPNavScreenAppearance.vue
- src/vitepress/components/VPNotFound.vue
- src/vitepress/components/VPSidebar.vue
- src/vitepress/components/VPSkipLink.vue
- src/vitepress/config.ts
- src/vitepress/support/sidebar.ts
- tsconfig.json
Support i18n messages by adding a new optional field: `themeConfig.messages` to the config. More details:
```js
const config = {
// ...
themeConfig: {
// ...
messages: {
// basic-level
search: 'Search',
previous: 'Previous',
next: 'Next',
menu: 'Menu',
appearance: 'Appearance',
meta: 'Meta',
// block-level
pageNotFound: 'Page Not Found',
tableOfContents: 'Table of Contents for current page',
mainNavigation: 'Main Navigation',
mobileNavigation: 'Mobile Navigation',
sidebarNavigation: 'Sidebar Navigation',
// sentence-level
announcer: {
before: '',
after: ' has loaded'
},
footerLicense: {
before: 'Released under the ',
after: '.'
},
deadLinkFound: {
before: 'You found a dead link: ',
after: ''
},
deadLinkReport: {
before: 'Please ',
content: 'let us know',
after: ' so we can fix it.'
},
// …
```
> Support i18n messages

- src/vitepress/components/VPFooter.vue
Added horizontal padding to the footer for Vue.js document of Chinese and Japanese.
- Chinese (https://cn.vuejs.org/)
↓
- Japanese (in progress)
↓
> add padding to footer

- src/vitepress/composables/outline.ts
Checked in both Chrome and Edge, at bottom of page, `window.scrollY + window.innerHeight` > `document.body.offsetHeight`, last one didn't be highlighted
> fix: page bottom - highlight last outline link

- src/core/components/VTFlyout.vue
- src/core/styles/index.css
- src/core/styles/vt-locales.css
- src/core/types/menu.ts
- src/vitepress/components/VPNavBarLocale.vue
- src/vitepress/components/VPNavBarLocaleItems.vue
- src/vitepress/components/VPNavBarLocaleJoin.vue
- src/vitepress/components/VPNavBarMenu.vue
- src/vitepress/components/VPNavBarScreenLocale.vue
- src/vitepress/components/VPNavScreen.vue
- src/vitepress/config.ts
This is a feature implementation of https://github.com/vuejs/docs/issues/2095
@yyx990803 Please take a look ~
```typescript
import type { Config as ThemeConfig } from '@vue/theme'
export default defineConfigWithTheme<ThemeConfig>({
themeConfig: {
...,
localeLinks: [
{
link: 'https://cn.vuejs.org',
text: '简体中文', 
repo: 'https://github.com/vuejs-translations/docs-zh-cn' 
}, 
{ 
link: 'https://ja.vuejs.org', 
text: '日本語', 
repo: 'https://github.com/vuejs-translations/docs-ja'
},
{ 
link: '/translations/', 
text: 'Join in translation', 
isTranslationsDesc: true 
}
],
}
})
```
> it goes to the same page (with matching hash) of that translation.
Click the github icon, can navigate to translation repo page. the URL is provided by the theme configuration `localeLinks`, which we've shown above. …
> feat(theme): add locales dropdown

- demo/guide/installation.md
- src/core/styles/base.css
A long link from vue playground:
> fix: break long words on overflow

- demo/.vitepress/config.js
- src/core/components/VTSwitchAppearance.vue
- src/vitepress/components/VPNavBarLocale.vue
- src/vitepress/components/VPNavBarLocaleItems.vue
- src/vitepress/components/VPNavBarLocaleJoin.vue
- src/vitepress/config.ts
I found that some components lack accessibility label.
About VTSwitchAppearance: the aria-checked attribute is required in `role="switch"`.
> fix: accessibility improvement

- src/core/styles/vt-flyout.css
- src/core/styles/vt-menu.css
By adding a calculated max height to the VT Flyout menu and an overflow auto to the VT Menu, this makes the submenu fully accessible again :)
https://user-images.githubusercontent.com/2922851/228395761-bc2ccbf9-ab04-466f-947d-dc9e111b6ca6.mp4
Fixes #91
> fix: add calculated max height and overflow auto

- src/core/styles/vt-flyout.css
This is able to be reproduced on vuejs homepage:
Before with banner
Before without banner
After with banner
After without banner
> fix: flyout menu height with banner

- src/vitepress/components/VPContentDocFooter.vue
- src/vitepress/support/utils.ts
When deploing Vue doc project on local environment with base URL configuration, the sidebar link active status is wrong. And footer link is wrong also.
This PR fix this issue to make local deployment experience better.
> fix: fixup link related error after configurating base URL

- src/vitepress/components/VPDocOutlineItem.vue
syncing with vitepress changes - it might be possible that the data returned by mdit-vue/plugin-headers has already escaped html entities (e.g. `&amp;`). using moustache syntax would result in that being rendered as-is while we want to render simply `&` there.
> fix: don't escape entities in headers again

- package.json
- pnpm-lock.yaml
- src/vitepress/components/VPDocOutlineItem.vue
fixes the concerns in #106
/cc @Jinjiang you can try something like this in `demo/guide/introduction.md` to test:
```md
```
The browser bundle only has this code (<200B after gzip/br):
```ts
const n=/&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-fA-F]{1,6});?/gi;let t;function o(e){return t||(t=new DOMParser),t.parseFromString(e,"text/html").documentElement.textContent}function c(e){return n.lastIndex=0,e.replace(n,r=>o(r))
```
unminified:
```ts
const ENTITY_RE = /&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-fA-F]{1,6});?/gi;
let p;
function decodeHTML5(value) {
if (!p)
p = new DOMParser();
return p.parseFromString(value, "text/html").documentElement.textContent;
}
function decode(value) {
ENTITY_RE.lastIndex = 0;
return value.replace(ENTITY_RE, (m) => decodeHTML5(m));
}
```
> chore: use tiny-decode instead of v-html+escapeHtml

- src/vitepress/components/VPNavBarSearch.vue
> fix: search style after docsearch run

- src/vitepress/components/VPNavBarSearch.vue
Before:
After:
> Both with network throttling applied under Fast 4G.
> fix: flicker on docsearch button while loading the search component

- .gitignore
- src/core/components/VTFlyout.vue
- src/core/components/VTLink.vue
- src/core/components/VTMenuBadge.vue
- src/core/components/VTMenuLink.vue
- src/core/styles/index.css
- src/core/styles/vt-menu-badge.css
- src/core/types/menu.ts
- src/vitepress/components/VPNavBarMenuGroup.vue
- src/vitepress/components/VPNavBarMenuLink.vue
- src/vitepress/components/VPNavScreenMenu.vue
- src/vitepress/components/VPNavScreenMenuGroup.vue
- src/vitepress/components/VPNavScreenMenuGroupLink.vue
- src/vitepress/components/VPNavScreenMenuGroupSection.vue
- src/vitepress/components/VPNavScreenMenuLink.vue
- src/vitepress/components/VPSidebar.vue
- src/vitepress/components/VPSidebarGroup.vue
- src/vitepress/components/VPSidebarLink.vue
- src/vitepress/config.ts
Do you want to highlight a link to a **_new_** page, a link to a **_beta_** feature, or any other purpose?
Now it is possible by adding `badge` property to **nav** or **sidebar** configs
```javascript
{
text: 'Sponsor',
badge: { text: 'beta' },
link: '/sponsor/'
}
``` 
Additionally, you can specify the color of the badge
```javascript
{
text: 'Sponsor',
badge: { text: 'beta', type: 'success' }, // available types - 'primary' | 'secondary' | 'success' | 'info' | 'warning' | 'danger'
link: '/sponsor/'
}
``` 
**NOTE: This feature is required to be able to highlight the upcoming "Developers" partner page on vuejs.org website.**
> Add badge support to navigation and sidebar

- src/core/styles/variables.css
There are multiple issues about Courier New being awful-looking on Linux:
- [Bootstrap](https://github.com/twbs/bootstrap/issues/18609)
- [Chromium](https://issues.chromium.org/issues/40260598)
- [Vue.js Docs](https://github.com/vuejs/docs/issues/3105)
Courier New is only readable under Windows because [ClearType made a special case for it](https://learn.microsoft.com/en-us/archive/blogs/fontblog/why-is-courier-new-so-thin).
Therefore, it should never be one's first choice for monospace font. It should be put at the end of the list.
By the way, though Courier New is a proprietary font, it is available on Linux through [Microsoft's Core Fonts for the Web](https://en.wikipedia.org/wiki/Core_fonts_for_the_Web). That's why Linux users might see it.
In this PR I propose we set the monospace …
> fix: put all kinds of system monospace fonts before Courier New
